### PR TITLE
Add bot latency to scheduled feed

### PR DESCRIPTION
**Pull request by RidgewayPlus**
changed something . This is more accurate because it tests both ways, as ping should.

### CODE REVIEW

**Comment by RidgewayPlus** [comment]
The old method only checked round trip, this checks both ways using API Latency and bot latency or something

**Review by cleverActon0126 — CHANGES_REQUESTED** [review]
"msg" is not defined

**Comment by RidgewayPlus** [comment]
> "msg" is not defined
using bot instead like the last ?

**Comment by cleverActon0126** [comment]
nope, you gotta define the message that was sent, then edit the message using the defined message with message.createdTimestamp - msg.createdTimestamp

**Comment by cleverActon0126** [comment]
Over taken by commit 0d6257fe143f75e81ab1afc89ddbab296a0cc944.

**Pull request closed without merging**
